// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {gui} from '../models';

export function AddProfile(arg1:config.ProfileConfig):Promise<void>;

export function AddUser(arg1:config.UserConfig):Promise<void>;

export function ConfigSnapshot():Promise<config.Config>;

export function DigitalInput(arg1:string,arg2:boolean):Promise<void>;

export function ImageTooBlurry(arg1:string,arg2:boolean):Promise<void>;

export function ImageTooBright(arg1:string,arg2:boolean):Promise<void>;

export function ImageTooDark(arg1:string,arg2:boolean):Promise<void>;

export function Motion(arg1:string,arg2:boolean):Promise<void>;

export function PublishRaw(arg1:string,arg2:string):Promise<void>;

export function RemoveProfile(arg1:string):Promise<void>;

export function RemoveUser(arg1:string):Promise<void>;

export function Running():Promise<boolean>;

export function SetAuthEnabled(arg1:boolean):Promise<void>;

export function SetDiscoveryMode(arg1:string):Promise<void>;

export function SetEventsTopics(arg1:Array<config.TopicConfig>):Promise<void>;

export function SetHostname(arg1:string):Promise<void>;

export function SetProfileEncoder(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number):Promise<void>;

export function SetProfileRTSP(arg1:string,arg2:string):Promise<void>;

export function SetProfileSnapshotURI(arg1:string,arg2:string):Promise<void>;

export function SetTopicEnabled(arg1:string,arg2:boolean):Promise<void>;

export function Start():Promise<void>;

export function Status():Promise<gui.Status>;

export function Stop():Promise<void>;

export function SyncProperty(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function UpsertUser(arg1:config.UserConfig):Promise<void>;

export function Users():Promise<Array<gui.UserView>>;
