// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['gui']['App']['AddProfile'](arg1);
}

export function AddUser(arg1) {
  return window['go']['gui']['App']['AddUser'](arg1);
}

export function ClearLogs() {
  return window['go']['gui']['App']['ClearLogs']();
}

export function ConfigSnapshot() {
  return window['go']['gui']['App']['ConfigSnapshot']();
}

export function DigitalInput(arg1, arg2) {
  return window['go']['gui']['App']['DigitalInput'](arg1, arg2);
}

export function GetLogs(arg1, arg2) {
  return window['go']['gui']['App']['GetLogs'](arg1, arg2);
}

export function ImageTooBlurry(arg1, arg2) {
  return window['go']['gui']['App']['ImageTooBlurry'](arg1, arg2);
}

export function ImageTooBright(arg1, arg2) {
  return window['go']['gui']['App']['ImageTooBright'](arg1, arg2);
}

export function ImageTooDark(arg1, arg2) {
  return window['go']['gui']['App']['ImageTooDark'](arg1, arg2);
}

export function Motion(arg1, arg2) {
  return window['go']['gui']['App']['Motion'](arg1, arg2);
}

export function PickMediaFile() {
  return window['go']['gui']['App']['PickMediaFile']();
}

export function PublishRaw(arg1, arg2) {
  return window['go']['gui']['App']['PublishRaw'](arg1, arg2);
}

export function RemoveProfile(arg1) {
  return window['go']['gui']['App']['RemoveProfile'](arg1);
}

export function RemoveUser(arg1) {
  return window['go']['gui']['App']['RemoveUser'](arg1);
}

export function Running() {
  return window['go']['gui']['App']['Running']();
}

export function SetAuthEnabled(arg1) {
  return window['go']['gui']['App']['SetAuthEnabled'](arg1);
}

export function SetDiscoveryMode(arg1) {
  return window['go']['gui']['App']['SetDiscoveryMode'](arg1);
}

export function SetEventsTopics(arg1) {
  return window['go']['gui']['App']['SetEventsTopics'](arg1);
}

export function SetHostname(arg1) {
  return window['go']['gui']['App']['SetHostname'](arg1);
}

export function SetProfileMediaFile(arg1, arg2) {
  return window['go']['gui']['App']['SetProfileMediaFile'](arg1, arg2);
}

export function SetProfileSnapshotURI(arg1, arg2) {
  return window['go']['gui']['App']['SetProfileSnapshotURI'](arg1, arg2);
}

export function SetTopicEnabled(arg1, arg2) {
  return window['go']['gui']['App']['SetTopicEnabled'](arg1, arg2);
}

export function Start() {
  return window['go']['gui']['App']['Start']();
}

export function Status() {
  return window['go']['gui']['App']['Status']();
}

export function Stop() {
  return window['go']['gui']['App']['Stop']();
}

export function SyncProperty(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['gui']['App']['SyncProperty'](arg1, arg2, arg3, arg4, arg5);
}

export function UpsertUser(arg1) {
  return window['go']['gui']['App']['UpsertUser'](arg1);
}

export function Users() {
  return window['go']['gui']['App']['Users']();
}
