// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function ConfigSnapshot() {
  return window['go']['main']['App']['ConfigSnapshot']();
}

export function DigitalInput(arg1, arg2) {
  return window['go']['main']['App']['DigitalInput'](arg1, arg2);
}

export function ImageTooBlurry(arg1, arg2) {
  return window['go']['main']['App']['ImageTooBlurry'](arg1, arg2);
}

export function ImageTooBright(arg1, arg2) {
  return window['go']['main']['App']['ImageTooBright'](arg1, arg2);
}

export function ImageTooDark(arg1, arg2) {
  return window['go']['main']['App']['ImageTooDark'](arg1, arg2);
}

export function Motion(arg1, arg2) {
  return window['go']['main']['App']['Motion'](arg1, arg2);
}

export function PublishRaw(arg1, arg2) {
  return window['go']['main']['App']['PublishRaw'](arg1, arg2);
}

export function RemoveProfile(arg1) {
  return window['go']['main']['App']['RemoveProfile'](arg1);
}

export function RemoveUser(arg1) {
  return window['go']['main']['App']['RemoveUser'](arg1);
}

export function Running() {
  return window['go']['main']['App']['Running']();
}

export function SetAuthEnabled(arg1) {
  return window['go']['main']['App']['SetAuthEnabled'](arg1);
}

export function SetDiscoveryMode(arg1) {
  return window['go']['main']['App']['SetDiscoveryMode'](arg1);
}

export function SetEventsTopics(arg1) {
  return window['go']['main']['App']['SetEventsTopics'](arg1);
}

export function SetHostname(arg1) {
  return window['go']['main']['App']['SetHostname'](arg1);
}

export function SetProfileEncoder(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SetProfileEncoder'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetProfileRTSP(arg1, arg2) {
  return window['go']['main']['App']['SetProfileRTSP'](arg1, arg2);
}

export function SetProfileSnapshotURI(arg1, arg2) {
  return window['go']['main']['App']['SetProfileSnapshotURI'](arg1, arg2);
}

export function SetTopicEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTopicEnabled'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function SyncProperty(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SyncProperty'](arg1, arg2, arg3, arg4, arg5);
}

export function UpsertUser(arg1) {
  return window['go']['main']['App']['UpsertUser'](arg1);
}

export function Users() {
  return window['go']['main']['App']['Users']();
}
