name: Coverage

on:
  pull_request:

jobs:
  coverage:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: .go-version
          cache: true

      - name: Run tests with coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          fail_ci_if_error: true
